In [1]:
# Import the required libraries
import osmnx as ox
import geopandas as gpd
from shapely.geometry import MultiPolygon

# Define the area to fetch data for
place_name = "Banepa, Nepal"

# Fetch the building data
building_data = ox.geometries_from_place(place_name, tags={'building': True})

# Convert Polygon geometries to MultiPolygon
building_data['geometry'] = building_data['geometry'].apply(lambda x: MultiPolygon([x]) if x.geom_type == 'Polygon' else x)

# Calculate the centroid of each building
building_data['centroid'] = building_data['geometry'].centroid

# Extract latitude and longitude of the centroid
building_data['latitude'] = building_data['centroid'].apply(lambda point: point.y)
building_data['longitude'] = building_data['centroid'].apply(lambda point: point.x)

# Save the building data as a shapefile
# building_data.to_file("banepa_buildings.shp")

# Save the building data as a GeoJSON file
# building_data.to_file("banepa_buildings.geojson", driver='GeoJSON')

# Display the first few rows of the GeoDataFrame
print(building_data[['geometry', 'centroid', 'latitude', 'longitude']].head())

/var/folders/zz/qg9mqbp56631kxmjjyl11f1h0000gn/T/ipykernel_22085/1643871790.py:10: UserWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in a future release.
  building_data = ox.geometries_from_place(place_name, tags={'building': True})
/var/folders/zz/qg9mqbp56631kxmjjyl11f1h0000gn/T/ipykernel_22085/1643871790.py:16: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  building_data['centroid'] = building_data['geometry'].centroid

                                          geometry                   centroid  \
element_type osmid
node         2194091454  POINT (85.52077 27.62936)  POINT (85.52077 27.62936)
             3079597823  POINT (85.51787 27.63385)  POINT (85.51787 27.63385)
             6487597596  POINT (85.52108 27.69282)  POINT (85.52108 27.69282)
             6516218528  POINT (85.51500 27.62789)  POINT (85.51500 27.62789)
             9819320839  POINT (85.52341 27.63669)  POINT (85.52341 27.63669)

                          latitude  longitude
element_type osmid
node         2194091454  27.629361  85.520773
             3079597823  27.633853  85.517867
             6487597596  27.692825  85.521084
             6516218528  27.627886  85.515002
             9819320839  27.636694  85.523407

In [2]:
# remove empty name, lat, lon from data

data = building_data.dropna(subset=['latitude', 'longitude'])
data

                        addr:housenumber building  \
element_type osmid
node         2194091454                6    house
             3079597823              NaN   temple
             6487597596              NaN      yes
             6516218528              NaN      yes
             9819320839              NaN      yes
...                                  ...      ...
way          1164756274              NaN      yes
             1164756602              NaN      yes
             1188419423              NaN      yes
relation     14419761                NaN      yes
             14486641                NaN      yes

                                                  name old_name  \
element_type osmid
node         2194091454           krishan prasad niwas   banepa
             3079597823              चन्देश्वरी मन्दिर      NaN
             6487597596  Nagarkot Geodetic Observatory      NaN
             6516218528                            NaN      NaN
             9819320839                            NaN      NaN
...                                                ...      ...
way          1164756274                            NaN      NaN
             1164756602                            NaN      NaN
             1188419423                            NaN      NaN
relation     14419761                              NaN      NaN
             14486641                              NaN      NaN

                                                                  geometry  \
element_type osmid
node         2194091454                          POINT (85.52077 27.62936)
             3079597823                          POINT (85.51787 27.63385)
             6487597596                          POINT (85.52108 27.69282)
             6516218528                          POINT (85.51500 27.62789)
             9819320839                          POINT (85.52341 27.63669)
...                                                                    ...
way          1164756274  MULTIPOLYGON (((85.49039 27.63990, 85.49043 27...
             1164756602  MULTIPOLYGON (((85.48590 27.63561, 85.48589 27...
             1188419423  MULTIPOLYGON (((85.49240 27.63580, 85.49244 27...
relation     14419761    MULTIPOLYGON (((85.51320 27.64548, 85.51323 27...
             14486641    MULTIPOLYGON (((85.51774 27.63629, 85.51765 27...

                        roof:material roof:shape           amenity  \
element_type osmid
node         2194091454           NaN        NaN               NaN
             3079597823           NaN        NaN  place_of_worship
             6487597596           NaN        NaN               NaN
             6516218528           NaN        NaN               NaN
             9819320839           tin       flat               NaN
...                               ...        ...               ...
way          1164756274           NaN        NaN               NaN
             1164756602           NaN        NaN               NaN
             1188419423           NaN        NaN               NaN
relation     14419761             NaN        NaN               NaN
             14486641        concrete       flat               NaN

                                     name:en            name:ne  ... material  \
element_type osmid                                               ...
node         2194091454                  NaN                NaN  ...      NaN
             3079597823  chandeshwori temple  चन्देश्वरी मन्दिर  ...      NaN
             6487597596                  NaN                NaN  ...      NaN
             6516218528                  NaN                NaN  ...      NaN
             9819320839                  NaN                NaN  ...      NaN
...                                      ...                ...  ...      ...
way          1164756274                  NaN                NaN  ...      NaN
             1164756602                  NaN                NaN  ...      NaN
             1188419423                  NaN                NaN  ...      NaN
relation     14419761                    NaN                NaN  ...      NaN
             14486641                    NaN                NaN  ...      NaN

                        sloar_panel garden:type solar:panel product  \
element_type osmid
node         2194091454         NaN         NaN         NaN     NaN
             3079597823         NaN         NaN         NaN     NaN
             6487597596         NaN         NaN         NaN     NaN
             6516218528         NaN         NaN         NaN     NaN
             9819320839         NaN         NaN         NaN     NaN
...                             ...         ...         ...     ...
way          1164756274         NaN         NaN         NaN     NaN
             1164756602         NaN         NaN         NaN     NaN
             1188419423         NaN         NaN         NaN     NaN
relation     14419761           NaN         NaN         NaN     NaN
             14486641           NaN         NaN         NaN     NaN

                                            ways          type  \
element_type osmid
node         2194091454                      NaN           NaN
             3079597823                      NaN           NaN
             6487597596                      NaN           NaN
             6516218528                      NaN           NaN
             9819320839                      NaN           NaN
...                                          ...           ...
way          1164756274                      NaN           NaN
             1164756602                      NaN           NaN
             1188419423                      NaN           NaN
relation     14419761    [1083556229, 344763945]  multipolygon
             14486641    [288862361, 1088193052]  multipolygon

                                          centroid   latitude  longitude
element_type osmid
node         2194091454  POINT (85.52077 27.62936)  27.629361  85.520773
             3079597823  POINT (85.51787 27.63385)  27.633853  85.517867
             6487597596  POINT (85.52108 27.69282)  27.692825  85.521084
             6516218528  POINT (85.51500 27.62789)  27.627886  85.515002
             9819320839  POINT (85.52341 27.63669)  27.636694  85.523407
...                                            ...        ...        ...
way          1164756274  POINT (85.49044 27.63987)  27.639867  85.490442
             1164756602  POINT (85.48596 27.63557)  27.635567  85.485961
             1188419423  POINT (85.49246 27.63578)  27.635777  85.492461
relation     14419761    POINT (85.51315 27.64541)  27.645406  85.513151
             14486641    POINT (85.51771 27.63634)  27.636341  85.517705

[22526 rows x 95 columns]

In [3]:
data.to_csv("banepa_buildings.csv", index=False)